<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE TEI [
    <!ELEMENT TEI (header, facsimile?, text+)>
    <!ELEMENT header (#PCDATA)>
    <!ELEMENT facsimile (#PCDATA)>
    <!ELEMENT text (#PCDATA)>
]>

<!--Definirei seguenti elementi:
 elemento root:TEI
 elementi figli:
    header(obbligatorio una occorrenza)
    facsimile(opzionale una occorrenza)
    text(obbligatorio almeno una occorrenza)
 Gli elementi header, facsimile e text hanno tutti un content model testuale-->

<TEI>
    <header>
        Header
    </header>
    <facsimile>
        Facsimile
    </facsimile>
    <text>
        Text
    </text>
    <text>
        Text
    </text>
</TEI>